"""Output validation for planner agent responses.

Verifies that the planner's text output is grounded in tool call results --
every physiological number should trace back to a tool invocation, not be
fabricated by the LLM.

Phase 2 implements a simplified version that checks structural requirements:
- compute_training_stress was called at least once
- validate_progression_constraints was called at least once
- All tool calls succeeded

Future phases will add full numeric traceability (matching every number in the
plan text to a specific tool output).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ValidationResult:
    """Result of validating a planner's output against tool call evidence.

    Attributes:
        passed: True if all validation checks passed.
        issues: List of human-readable descriptions of validation failures.
            Empty when passed is True.
    """

    passed: bool
    issues: list[str] = field(default_factory=list)


def validate_plan_output(
    plan_text: str,
    tool_calls: list[dict[str, Any]],
) -> ValidationResult:
    """Validate that the planner's output is properly grounded in tool calls.

    Phase 2 checks:
    1. The plan text is non-empty.
    2. compute_training_stress was called at least once (workouts must have
       tool-computed TSS values).
    3. validate_progression_constraints was called at least once (safety
       validation is mandatory before finalizing any plan).
    4. All tool calls that were made succeeded (no unresolved errors).

    Args:
        plan_text: The raw text response from the planner agent.
        tool_calls: List of tool call records, each a dict with keys:
            name (str), input (dict), output (dict), success (bool).

    Returns:
        ValidationResult with passed=True if all checks pass, otherwise
        passed=False with a list of specific issues found.
    """
    issues: list[str] = []

    # Check 1: Non-empty plan text
    if not plan_text or not plan_text.strip():
        issues.append("Plan text is empty. The planner did not produce a response.")

    # Check 2: compute_training_stress must have been called
    stress_calls = [tc for tc in tool_calls if tc["name"] == "compute_training_stress"]
    if not stress_calls:
        issues.append(
            "compute_training_stress was never called. All workout TSS values "
            "must be computed by tools, not generated by the LLM."
        )

    # Check 3: validate_progression_constraints must have been called
    validation_calls = [
        tc for tc in tool_calls if tc["name"] == "validate_progression_constraints"
    ]
    if not validation_calls:
        issues.append(
            "validate_progression_constraints was never called. Safety validation "
            "is mandatory before finalizing any training plan."
        )

    # Check 4: All tool calls should have succeeded
    failed_calls = [tc for tc in tool_calls if not tc.get("success", False)]
    if failed_calls:
        failed_names = [tc["name"] for tc in failed_calls]
        issues.append(
            f"{len(failed_calls)} tool call(s) failed: {', '.join(failed_names)}. "
            "The planner should retry failed tool calls or adjust inputs."
        )

    return ValidationResult(
        passed=len(issues) == 0,
        issues=issues,
    )
