"""Training plan domain models."""

from enum import Enum

from pydantic import BaseModel, Field

from src.models.workout import Workout, WorkoutType


class TrainingPhase(str, Enum):
    """Macrocycle phases for periodized training."""

    BASE = "base"
    BUILD = "build"
    PEAK = "peak"
    TAPER = "taper"
    RECOVERY = "recovery"


class PlanWeek(BaseModel):
    """A single week within a training plan.

    Attributes:
        week_number: 1-indexed week number within the plan.
        phase: The macrocycle phase this week belongs to.
        workouts: List of workouts prescribed for the week.
        target_load: Target total training stress for the week
            (computed by tools).
        actual_load: Actual total stress after logging (computed by tools).
        notes: Planner notes explaining the week's focus.
    """

    week_number: int = Field(ge=1, description="1-indexed week number")
    phase: TrainingPhase
    workouts: list[Workout] = Field(default_factory=list)
    target_load: float | None = Field(
        default=None, description="Target weekly TSS (computed by tools)"
    )
    actual_load: float | None = Field(
        default=None, description="Actual weekly TSS from logged workouts"
    )
    notes: str = Field(default="", description="Planner notes for this week")

    @property
    def total_distance_km(self) -> float:
        """Sum of all workout distances in the week."""
        return sum(w.distance_km for w in self.workouts)

    @property
    def total_duration_minutes(self) -> float:
        """Sum of all workout durations in the week."""
        return sum(w.duration_minutes for w in self.workouts)

    @property
    def training_days(self) -> int:
        """Count of non-rest workout days."""
        return sum(1 for w in self.workouts if w.workout_type != WorkoutType.REST)


class TrainingPlan(BaseModel):
    """A complete training plan generated by the planner agent.

    Attributes:
        athlete_name: Name of the athlete this plan is for.
        goal_event: Target race distance (e.g., "marathon").
        goal_date: Target race date as ISO string (YYYY-MM-DD).
        weeks: Ordered list of plan weeks.
        predicted_finish_time_minutes: Monte Carlo predicted finish time.
        notes: High-level plan rationale from the planner.
    """

    athlete_name: str
    goal_event: str
    goal_date: str | None = Field(
        default=None, description="Race date (YYYY-MM-DD)"
    )
    weeks: list[PlanWeek] = Field(default_factory=list)
    predicted_finish_time_minutes: float | None = Field(
        default=None, description="Predicted finish time (from simulation tool)"
    )
    notes: str = Field(default="", description="High-level plan rationale")

    @property
    def total_weeks(self) -> int:
        """Total number of weeks in the plan."""
        return len(self.weeks)

    @property
    def phase_distribution(self) -> dict[str, int]:
        """Count of weeks in each training phase."""
        dist: dict[str, int] = {}
        for week in self.weeks:
            dist[week.phase] = dist.get(week.phase, 0) + 1
        return dist
