"""add invite_requests table

Revision ID: 12168dc934a9
Revises: c3e8a71f5d20
Create Date: 2026-03-28 12:18:57.647015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12168dc934a9'
down_revision: Union[str, Sequence[str], None] = 'c3e8a71f5d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'denied')", name='ck_invite_request_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invite_requests_user', 'invite_requests', ['user_id'], unique=False)
    # Partial unique index: only one pending request per user
    op.execute(
        "CREATE UNIQUE INDEX uq_invite_requests_pending "
        "ON invite_requests (user_id) WHERE status = 'pending'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_invite_requests_pending")
    op.drop_index('idx_invite_requests_user', table_name='invite_requests')
    op.drop_table('invite_requests')
    # ### end Alembic commands ###
