"""add preferred_units to athlete_profiles

Revision ID: a4d58c24e1dc
Revises: f75f238710e0
Create Date: 2026-03-23 18:52:33.721208

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4d58c24e1dc"
down_revision: str | Sequence[str] | None = "f75f238710e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "preferred_units", sa.String(length=10), nullable=False, server_default="metric"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("athlete_profiles", "preferred_units")
    # ### end Alembic commands ###
