"""initial schema

Revision ID: f75f238710e0
Revises:
Create Date: 2026-03-21 11:27:58.913422

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f75f238710e0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("auth_provider", sa.String(length=20), nullable=False),
        sa.Column("auth_provider_id", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_provider", "auth_provider_id", name="uq_auth_provider_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "athlete_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("vo2max", sa.Float(), nullable=True),
        sa.Column("vdot", sa.Float(), nullable=True),
        sa.Column("weekly_mileage_base", sa.Float(), nullable=False),
        sa.Column("hr_max", sa.Integer(), nullable=True),
        sa.Column("hr_rest", sa.Integer(), nullable=True),
        sa.Column("injury_history", sa.Text(), nullable=False),
        sa.Column("risk_tolerance", sa.String(length=20), nullable=False),
        sa.Column("max_weekly_increase_pct", sa.Float(), nullable=False),
        sa.Column("goal_distance", sa.String(length=50), nullable=False),
        sa.Column("goal_time_minutes", sa.Float(), nullable=True),
        sa.Column("training_days_per_week", sa.Integer(), nullable=False),
        sa.Column("long_run_cap_pct", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("age BETWEEN 10 AND 100", name="ck_age_range"),
        sa.CheckConstraint(
            "hr_max IS NULL OR (hr_max BETWEEN 100 AND 230)", name="ck_hr_max_range"
        ),
        sa.CheckConstraint(
            "hr_rest IS NULL OR (hr_rest BETWEEN 30 AND 100)", name="ck_hr_rest_range"
        ),
        sa.CheckConstraint("vdot IS NULL OR (vdot BETWEEN 15.0 AND 85.0)", name="ck_vdot"),
        sa.CheckConstraint("vo2max IS NULL OR (vo2max BETWEEN 15.0 AND 90.0)", name="ck_vo2max"),
        sa.CheckConstraint("weekly_mileage_base >= 0", name="ck_mileage_positive"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "strava_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("strava_athlete_id", sa.BigInteger(), nullable=False),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("strava_athlete_id"),
    )
    op.create_table(
        "training_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "athlete_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plan_data",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "decision_log",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "scores",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'superseded', 'archived')", name="ck_plan_status"
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["training_plans.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_plans_user_status", "training_plans", ["user_id", "status"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["training_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_chat_plan", "chat_messages", ["plan_id", "created_at"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("job_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "progress",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["training_plans.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_jobs_user", "jobs", ["user_id"], unique=False)
    op.create_table(
        "workout_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("strava_activity_id", sa.BigInteger(), nullable=True),
        sa.Column("actual_distance_km", sa.Float(), nullable=False),
        sa.Column("actual_duration_minutes", sa.Float(), nullable=False),
        sa.Column("avg_heart_rate", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Integer(), nullable=True),
        sa.Column("actual_tss", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("day IS NULL OR (day BETWEEN 1 AND 7)", name="ck_day_range"),
        sa.CheckConstraint("rpe IS NULL OR (rpe BETWEEN 1 AND 10)", name="ck_rpe_range"),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["training_plans.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strava_activity_id"),
    )
    op.create_index(
        "idx_logs_user_date", "workout_logs", ["user_id", "completed_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_logs_user_date", table_name="workout_logs")
    op.drop_table("workout_logs")
    op.drop_index("idx_jobs_user", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("idx_chat_plan", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("idx_plans_user_status", table_name="training_plans")
    op.drop_table("training_plans")
    op.drop_table("strava_tokens")
    op.drop_table("athlete_profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
