"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useDemoPlan } from "@/lib/hooks";
import { PlanCalendar } from "@/components/PlanCalendar";
import { ScoreBadge, ScoreBadgeGroup } from "@/components/ScoreBadge";
import { Logo } from "@/components/Logo";

export default function DemoPlanPage() {
  const params = useParams();
  const planId = params.id as string;
  const { data: plan, isLoading, error } = useDemoPlan(planId);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-gray-500">Loading plan...</div>
      </div>
    );
  }

  if (error || !plan) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-xl font-semibold text-gray-900 mb-2">Plan not found</h1>
          <Link href="/demo" className="text-indigo-600 hover:text-indigo-700">
            &larr; Back to demo plans
          </Link>
        </div>
      </div>
    );
  }

  const planData = plan.plan_data;
  const snapshot = plan.athlete_snapshot as Record<string, unknown>;
  const weeks = planData.weeks ?? [];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/" className="flex items-center gap-2">
              <Logo size="sm" />
              <span className="text-lg font-semibold text-gray-900">MileMind</span>
            </Link>
            <span className="text-gray-300">|</span>
            <Link href="/demo" className="text-sm text-gray-500 hover:text-gray-700">
              Demo Plans
            </Link>
          </div>
          <Link
            href="/login"
            className="text-sm font-medium text-indigo-600 hover:text-indigo-700"
          >
            Sign in &rarr;
          </Link>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-8">
        {/* Demo banner */}
        <div className="bg-indigo-50 border border-indigo-200 rounded-lg px-4 py-3 mb-6 flex items-center justify-between">
          <p className="text-sm text-indigo-700">
            This is a demo plan generated by MileMind&apos;s AI system.{" "}
            <Link href="/login" className="font-medium underline">
              Sign up
            </Link>{" "}
            to generate your own.
          </p>
          <Link
            href={`/demo/${planId}/debug`}
            className="text-sm font-medium text-indigo-600 hover:text-indigo-800 whitespace-nowrap ml-4"
          >
            View AI Decision Log &rarr;
          </Link>
        </div>

        {/* Plan header */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">
                {planData.goal_event} Training Plan
              </h1>
              <p className="text-gray-500 mt-1">
                {(snapshot.name as string) || "Athlete"} &bull;{" "}
                {weeks.length} weeks &bull;{" "}
                {planData.predicted_finish_time_minutes
                  ? `Target: ${Math.floor(planData.predicted_finish_time_minutes / 60)}h ${Math.round(planData.predicted_finish_time_minutes % 60)}m`
                  : ""}
              </p>
            </div>
            {plan.scores && (
              <div className="flex gap-2">
                <ScoreBadge dimension="safety" score={plan.scores.safety} />
                <ScoreBadge dimension="feasibility" score={plan.scores.feasibility} />
              </div>
            )}
          </div>

          {/* Athlete summary */}
          <div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-3 text-sm">
            <div className="bg-gray-50 rounded-lg p-3">
              <div className="text-gray-500 text-xs">Weekly Base</div>
              <div className="font-medium">{snapshot.weekly_mileage_base as number} km/week</div>
            </div>
            <div className="bg-gray-50 rounded-lg p-3">
              <div className="text-gray-500 text-xs">VDOT</div>
              <div className="font-medium">{(snapshot.vdot as number) || "N/A"}</div>
            </div>
            <div className="bg-gray-50 rounded-lg p-3">
              <div className="text-gray-500 text-xs">Risk Profile</div>
              <div className="font-medium capitalize">{snapshot.risk_tolerance as string}</div>
            </div>
            <div className="bg-gray-50 rounded-lg p-3">
              <div className="text-gray-500 text-xs">Training Days</div>
              <div className="font-medium">{snapshot.training_days_per_week as number}/week</div>
            </div>
          </div>

          {/* Final scores */}
          {plan.scores && (
            <div className="mt-4">
              <ScoreBadgeGroup scores={plan.scores} />
            </div>
          )}
        </div>

        {/* Plan notes */}
        {planData.notes && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-6">
            <h2 className="text-sm font-medium text-gray-700 mb-2">Plan Strategy</h2>
            <p className="text-sm text-gray-600 leading-relaxed">{planData.notes}</p>
          </div>
        )}

        {/* Calendar */}
        <PlanCalendar weeks={weeks} units={(snapshot.preferred_units as string) === "imperial" ? "imperial" : "metric"} />
      </main>
    </div>
  );
}
